meta_product_name: "Attack on Titan API"
meta_title: "Attack on Titan API"
meta_description: "This is a free, easy-to-use and open-source API for anime Attack on Titan built with Ruby and Ruby on Rails."
meta_image: "attack-on-titan.png"
twitter_account: "@ChenchenZheng_"
